/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as ResendOTP from "../ResendOTP.js";
import type * as VerificationCodeEmail from "../VerificationCodeEmail.js";
import type * as auth from "../auth.js";
import type * as common from "../common.js";
import type * as cronlib from "../cronlib.js";
import type * as cronvex from "../cronvex.js";
import type * as http from "../http.js";
import type * as init from "../init.js";
import type * as testUtils from "../testUtils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  VerificationCodeEmail: typeof VerificationCodeEmail;
  auth: typeof auth;
  common: typeof common;
  cronlib: typeof cronlib;
  cronvex: typeof cronvex;
  http: typeof http;
  init: typeof init;
  testUtils: typeof testUtils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
